//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.08 at 07:08:15 PM BRT 
//

package br.jrrombaldo.nmap.entity;

import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"status", "address", "hostnames", "smurf", "ports", "os", "distance", "uptime", "tcpsequence", "ipidsequence",
    "tcptssequence", "hostscript", "trace", "times"})
@XmlRootElement(name = "host")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
public class Host
{

	@XmlAttribute(name = "starttime")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	protected String starttime;
	@XmlAttribute(name = "endtime")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	protected String endtime;
	@XmlAttribute(name = "comment")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	protected String comment;

	@XmlElement(name = "status", type = Status.class)
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-04-26T03:03:24-03:00")
	protected Status status;

	@XmlElement(name = "address", type = Address.class)
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-04-26T03:03:24-03:00")
	protected List<Address> address;

	@XmlElement(name = "hostnames", type = Hostnames.class)
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-04-26T03:03:24-03:00")
	protected Hostnames hostnames;

	@XmlElement(name = "smurf", type = Smurf.class)
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-04-26T03:03:24-03:00")
	protected Smurf smurf;

	@XmlElement(name = "ports", type = Ports.class)
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-04-26T03:03:24-03:00")
	protected Ports ports;

	@XmlElement(name = "os", type = Os.class)
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-04-26T03:03:24-03:00")
	protected Os os;

	@XmlElement(name = "distance", type = Distance.class)
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-04-26T03:03:24-03:00")
	protected Distance distance;

	@XmlElement(name = "uptime", type = Uptime.class)
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-04-26T03:03:24-03:00")
	protected Uptime uptime;

	@XmlElement(name = "tcpsequence", type = Tcpsequence.class)
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-04-26T03:03:24-03:00")
	protected Tcpsequence tcpsequence;

	@XmlElement(name = "ipidsequence", type = Ipidsequence.class)
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-04-26T03:03:24-03:00")
	protected Ipidsequence ipidsequence;

	@XmlElement(name = "tcptssequence", type = Tcptssequence.class)
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-04-26T03:03:24-03:00")
	protected Tcptssequence tcptssequence;

	@XmlElement(name = "hostscript", type = Hostscript.class)
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-04-26T03:03:24-03:00")
	protected Hostscript hostscript;

	@XmlElement(name = "trace", type = Trace.class)
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-04-26T03:03:24-03:00")
	protected Trace trace;

	@XmlElement(name = "times", type = Times.class)
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-04-26T03:03:24-03:00")
	protected Times times;

	/**
	 * Gets the value of the starttime property.
	 * @return possible object is {@link String }
	 */
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	public String getStarttime ()
	{
		return starttime;
	}

	/**
	 * Sets the value of the starttime property.
	 * @param value allowed object is {@link String }
	 */
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	public void setStarttime (String value)
	{
		this.starttime = value;
	}

	/**
	 * Gets the value of the endtime property.
	 * @return possible object is {@link String }
	 */
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	public String getEndtime ()
	{
		return endtime;
	}

	/**
	 * Sets the value of the endtime property.
	 * @param value allowed object is {@link String }
	 */
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	public void setEndtime (String value)
	{
		this.endtime = value;
	}

	/**
	 * Gets the value of the comment property.
	 * @return possible object is {@link String }
	 */
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	public String getComment ()
	{
		return comment;
	}

	/**
	 * Sets the value of the comment property.
	 * @param value allowed object is {@link String }
	 */
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	public void setComment (String value)
	{
		this.comment = value;
	}

	public Status getStatus ()
	{
		return status;
	}

	public void setStatus (Status status)
	{
		this.status = status;
	}

	public List<Address> getAddress ()
	{
		return address;
	}

	public void setAddress (List<Address> address)
	{
		this.address = address;
	}

	public Hostnames getHostnames ()
	{
		return hostnames;
	}

	public void setHostnames (Hostnames hostnames)
	{
		this.hostnames = hostnames;
	}

	public Smurf getSmurf ()
	{
		return smurf;
	}

	public void setSmurf (Smurf smurf)
	{
		this.smurf = smurf;
	}

	public Ports getPorts ()
	{
		return ports;
	}

	public void setPorts (Ports ports)
	{
		this.ports = ports;
	}

	public Os getOs ()
	{
		return os;
	}

	public void setOs (Os os)
	{
		this.os = os;
	}

	public Distance getDistance ()
	{
		return distance;
	}

	public void setDistance (Distance distance)
	{
		this.distance = distance;
	}

	public Uptime getUptime ()
	{
		return uptime;
	}

	public void setUptime (Uptime uptime)
	{
		this.uptime = uptime;
	}

	public Tcpsequence getTcpsequence ()
	{
		return tcpsequence;
	}

	public void setTcpsequence (Tcpsequence tcpsequence)
	{
		this.tcpsequence = tcpsequence;
	}

	public Ipidsequence getIpidsequence ()
	{
		return ipidsequence;
	}

	public void setIpidsequence (Ipidsequence ipidsequence)
	{
		this.ipidsequence = ipidsequence;
	}

	public Tcptssequence getTcptssequence ()
	{
		return tcptssequence;
	}

	public void setTcptssequence (Tcptssequence tcptssequence)
	{
		this.tcptssequence = tcptssequence;
	}

	public Hostscript getHostscript ()
	{
		return hostscript;
	}

	public void setHostscript (Hostscript hostscript)
	{
		this.hostscript = hostscript;
	}

	public Trace getTrace ()
	{
		return trace;
	}

	public void setTrace (Trace trace)
	{
		this.trace = trace;
	}

	public Times getTimes ()
	{
		return times;
	}

	public void setTimes (Times times)
	{
		this.times = times;
	}

	/**
	 * Gets the value of the
	 * statusOrAddressOrHostnamesOrSmurfOrPortsOrOsOrDistanceOrUptimeOrTcpsequenceOrIpidsequenceOrTcptssequenceOrHostscriptOrTraceOrTimes
	 * property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present inside the
	 * JAXB object. This is why there is not a <CODE>set</CODE> method for the
	 * statusOrAddressOrHostnamesOrSmurfOrPortsOrOsOrDistanceOrUptimeOrTcpsequenceOrIpidsequenceOrTcptssequenceOrHostscriptOrTraceOrTimes
	 * property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getStatusOrAddressOrHostnamesOrSmurfOrPortsOrOsOrDistanceOrUptimeOrTcpsequenceOrIpidsequenceOrTcptssequenceOrHostscriptOrTraceOrTimes().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link br.com.ibliss.sigvu.portscanner.entity.Status }
	 * {@link br.com.ibliss.sigvu.portscanner.entity.Address }
	 * {@link br.com.ibliss.sigvu.portscanner.entity.Hostnames }
	 * {@link br.com.ibliss.sigvu.portscanner.entity.Smurf }
	 * {@link br.com.ibliss.sigvu.portscanner.entity.Ports }
	 * {@link br.com.ibliss.sigvu.portscanner.entity.Os }
	 * {@link br.com.ibliss.sigvu.portscanner.entity.Distance }
	 * {@link br.com.ibliss.sigvu.portscanner.entity.Uptime }
	 * {@link br.com.ibliss.sigvu.portscanner.entity.Tcpsequence }
	 * {@link br.com.ibliss.sigvu.portscanner.entity.Ipidsequence }
	 * {@link br.com.ibliss.sigvu.portscanner.entity.Tcptssequence }
	 * {@link br.com.ibliss.sigvu.portscanner.entity.Hostscript }
	 * {@link br.com.ibliss.sigvu.portscanner.entity.Trace }
	 * {@link br.com.ibliss.sigvu.portscanner.entity.Times }
	 */

}
