//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.08 at 07:08:15 PM BRT 
//

package br.jrrombaldo.nmap.entity;

import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"scaninfo", "verbose", "debugging", "taskbegin", "taskprogress", "taskend", "prescript", "postscript", "host",
    "output", "runstats"})
@XmlRootElement(name = "nmaprun")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
public class Nmaprun
{

	@XmlAttribute(name = "scanner", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	protected String scanner;
	@XmlAttribute(name = "args")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	protected String args;
	@XmlAttribute(name = "start")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	protected String start;
	@XmlAttribute(name = "startstr")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	protected String startstr;
	@XmlAttribute(name = "version", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	protected String version;
	@XmlAttribute(name = "profile_name")
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	protected String profileName;
	@XmlAttribute(name = "xmloutputversion", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	protected String xmloutputversion;
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	protected List<Scaninfo> scaninfo;
	@XmlElement(required = true)
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	protected Verbose verbose;
	@XmlElement(required = true)
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	protected Debugging debugging;

	@XmlElement(name = "taskbegin", type = Taskbegin.class)
	protected Taskbegin taskbegin;

	@XmlElement(name = "taskprogress", type = Taskprogress.class)
	protected Taskprogress taskprogress;

	@XmlElement(name = "taskend", type = Taskend.class)
	protected Taskend taskend;

	@XmlElement(name = "prescript", type = Prescript.class)
	protected Prescript prescript;

	@XmlElement(name = "postscript", type = Postscript.class)
	protected Postscript postscript;

	@XmlElement(name = "host", type = Host.class)
	protected List<Host> host;

	@XmlElement(name = "output", type = Output.class)
	protected Output output;

	@XmlElement(name = "runstats", type = Runstats.class)
	protected Runstats runstats;

	public Runstats getRunstats ()
	{
		return runstats;
	}

	public void setRunstats (Runstats runstats)
	{
		this.runstats = runstats;
	}

	public String getScanner ()
	{
		return scanner;
	}

	public void setScanner (String scanner)
	{
		this.scanner = scanner;
	}

	public String getArgs ()
	{
		return args;
	}

	public void setArgs (String args)
	{
		this.args = args;
	}

	public String getStart ()
	{
		return start;
	}

	public void setStart (String start)
	{
		this.start = start;
	}

	public String getStartstr ()
	{
		return startstr;
	}

	public void setStartstr (String startstr)
	{
		this.startstr = startstr;
	}

	public String getVersion ()
	{
		return version;
	}

	public void setVersion (String version)
	{
		this.version = version;
	}

	public String getProfileName ()
	{
		return profileName;
	}

	public void setProfileName (String profileName)
	{
		this.profileName = profileName;
	}

	public String getXmloutputversion ()
	{
		return xmloutputversion;
	}

	public void setXmloutputversion (String xmloutputversion)
	{
		this.xmloutputversion = xmloutputversion;
	}

	public List<Scaninfo> getScaninfo ()
	{
		return scaninfo;
	}

	public void setScaninfo (List<Scaninfo> scaninfo)
	{
		this.scaninfo = scaninfo;
	}

	public Verbose getVerbose ()
	{
		return verbose;
	}

	public void setVerbose (Verbose verbose)
	{
		this.verbose = verbose;
	}

	public Debugging getDebugging ()
	{
		return debugging;
	}

	public void setDebugging (Debugging debugging)
	{
		this.debugging = debugging;
	}

	public Taskbegin getTaskbegin ()
	{
		return taskbegin;
	}

	public void setTaskbegin (Taskbegin taskbegin)
	{
		this.taskbegin = taskbegin;
	}

	public Taskprogress getTaskprogress ()
	{
		return taskprogress;
	}

	public void setTaskprogress (Taskprogress taskprogress)
	{
		this.taskprogress = taskprogress;
	}

	public Taskend getTaskend ()
	{
		return taskend;
	}

	public void setTaskend (Taskend taskend)
	{
		this.taskend = taskend;
	}

	public Prescript getPrescript ()
	{
		return prescript;
	}

	public void setPrescript (Prescript prescript)
	{
		this.prescript = prescript;
	}

	public Postscript getPostscript ()
	{
		return postscript;
	}

	public void setPostscript (Postscript postscript)
	{
		this.postscript = postscript;
	}

	public List<Host> getHost ()
	{
		return host;
	}

	public void setHost (List<Host> host)
	{
		this.host = host;
	}

	public Output getOutput ()
	{
		return output;
	}

	public void setOutput (Output output)
	{
		this.output = output;
	}

}
