//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.08 at 07:08:15 PM BRT 
//

package br.jrrombaldo.nmap.entity;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element
 * interface generated in the br.com.ibliss.sigvu.nmao.out.beans package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java
 * representation for XML content. The Java representation of XML content can consist of
 * schema derived interfaces and classes representing the binding of schema type
 * definitions, element declarations and model groups. Factory methods for each of these
 * are provided in this class.
 */
@XmlRegistry
public class ObjectFactory
{

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema
	 * derived classes for package: br.com.ibliss.sigvu.nmao.out.beans
	 */
	public ObjectFactory ()
	{
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Port }
	 */
	public Port createPort ()
	{
		return new Port();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.State }
	 */
	public State createState ()
	{
		return new State();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Owner }
	 */
	public Owner createOwner ()
	{
		return new Owner();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Service }
	 */
	public Service createService ()
	{
		return new Service();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Script }
	 */
	public Script createScript ()
	{
		return new Script();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Smurf }
	 */
	public Smurf createSmurf ()
	{
		return new Smurf();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Postscript }
	 */
	public Postscript createPostscript ()
	{
		return new Postscript();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Nmaprun }
	 */
	public Nmaprun createNmaprun ()
	{
		return new Nmaprun();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Scaninfo }
	 */
	public Scaninfo createScaninfo ()
	{
		return new Scaninfo();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Verbose }
	 */
	public Verbose createVerbose ()
	{
		return new Verbose();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Debugging }
	 */
	public Debugging createDebugging ()
	{
		return new Debugging();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Taskbegin }
	 */
	public Taskbegin createTaskbegin ()
	{
		return new Taskbegin();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Taskprogress }
	 */
	public Taskprogress createTaskprogress ()
	{
		return new Taskprogress();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Taskend }
	 */
	public Taskend createTaskend ()
	{
		return new Taskend();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Prescript }
	 */
	public Prescript createPrescript ()
	{
		return new Prescript();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Host }
	 */
	public Host createHost ()
	{
		return new Host();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Output }
	 */
	public Output createOutput ()
	{
		return new Output();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Runstats }
	 */
	public Runstats createRunstats ()
	{
		return new Runstats();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Osfingerprint }
	 */
	public Osfingerprint createOsfingerprint ()
	{
		return new Osfingerprint();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Extrareasons }
	 */
	public Extrareasons createExtrareasons ()
	{
		return new Extrareasons();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Distance }
	 */
	public Distance createDistance ()
	{
		return new Distance();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Times }
	 */
	public Times createTimes ()
	{
		return new Times();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Tcpsequence }
	 */
	public Tcpsequence createTcpsequence ()
	{
		return new Tcpsequence();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Hosts }
	 */
	public Hosts createHosts ()
	{
		return new Hosts();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Hostnames }
	 */
	public Hostnames createHostnames ()
	{
		return new Hostnames();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Hostname }
	 */
	public Hostname createHostname ()
	{
		return new Hostname();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Finished }
	 */
	public Finished createFinished ()
	{
		return new Finished();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Os }
	 */
	public Os createOs ()
	{
		return new Os();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Portused }
	 */
	public Portused createPortused ()
	{
		return new Portused();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Osclass }
	 */
	public Osclass createOsclass ()
	{
		return new Osclass();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Osmatch }
	 */
	public Osmatch createOsmatch ()
	{
		return new Osmatch();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Status }
	 */
	public Status createStatus ()
	{
		return new Status();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Address }
	 */
	public Address createAddress ()
	{
		return new Address();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Ports }
	 */
	public Ports createPorts ()
	{
		return new Ports();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Uptime }
	 */
	public Uptime createUptime ()
	{
		return new Uptime();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Ipidsequence }
	 */
	public Ipidsequence createIpidsequence ()
	{
		return new Ipidsequence();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Tcptssequence }
	 */
	public Tcptssequence createTcptssequence ()
	{
		return new Tcptssequence();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Hostscript }
	 */
	public Hostscript createHostscript ()
	{
		return new Hostscript();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Trace }
	 */
	public Trace createTrace ()
	{
		return new Trace();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Hop }
	 */
	public Hop createHop ()
	{
		return new Hop();
	}

	/**
	 * Create an instance of {@link br.jrrombaldo.nmap.entity.Extraports }
	 */
	public Extraports createExtraports ()
	{
		return new Extraports();
	}

}
