//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.08 at 07:08:15 PM BRT 
//

package br.jrrombaldo.nmap.entity;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"finished", "hosts"})
@XmlRootElement(name = "runstats")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
public class Runstats
{

	@XmlElement(required = true)
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	protected Finished finished;
	@XmlElement(required = true)
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	protected Hosts hosts;

	/**
	 * Gets the value of the finished property.
	 * @return possible object is {@link br.jrrombaldo.nmap.entity.Finished }
	 */
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	public Finished getFinished ()
	{
		return finished;
	}

	/**
	 * Sets the value of the finished property.
	 * @param value allowed object is
	 *        {@link br.jrrombaldo.nmap.entity.Finished }
	 */
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	public void setFinished (Finished value)
	{
		this.finished = value;
	}

	/**
	 * Gets the value of the hosts property.
	 * @return possible object is {@link br.jrrombaldo.nmap.entity.Hosts }
	 */
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	public Hosts getHosts ()
	{
		return hosts;
	}

	/**
	 * Sets the value of the hosts property.
	 * @param value allowed object is {@link br.jrrombaldo.nmap.entity.Hosts }
	 */
	@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-06-08T07:08:15-03:00")
	public void setHosts (Hosts value)
	{
		this.hosts = value;
	}

}
